version: '2.1'
services:
    neo4j:
        container_name: dd_homework_2_neo4j
        image: neo4j:4.2.3
        ports:
            - 7474:7474
            - 7473:7473
            - 7687:7687
        restart: always
        environment:
            - NEO4J_AUTH=neo4j/password
        volumes:
            - ./data:/import
        healthcheck:
            test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("0.0.0.0:7687")))'
            interval: 1s
            timeout: 1s
            retries: 25 
    python:
        container_name: dd_homework_2_python
        build: 
            context: .
        volumes:
            - ./src:/scripts
        depends_on: 
            neo4j:
                condition: service_healthy
        entrypoint: [python, /scripts/initialize.py]
