version: '3.1'
services:
    postgres:
        container_name: dd_homework_1
        image: postgres:13.1
        ports:
            - "5454:5432"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=homework_1
        volumes:
            - ./init/flights.sql:/docker-entrypoint-initdb.d/1-flight.sql
            - ./init/hotels.sql:/docker-entrypoint-initdb.d/2-hotels.sql
            - ./init/accounts.sql:/docker-entrypoint-initdb.d/3-accounts.sql
            - ./src/transaction.sql:/sql/transaction.sql
        command: -c max_prepared_transactions=10
